heat_template_version: rocky

description: >
  Heat template to set up 3-node infrastructure, 1x Controller, 1x OCP, 1x Compute

parameters:
  dns_servers:
    type: comma_delimited_list
    default:
      - 8.8.8.8
      - 8.8.4.4
  ntp_servers: 
    type: comma_delimited_list
    default: []
  ssh_pub_key:
    type: string
  keypair: 
    type: string
    default: default
  controller_params:
    type: json
    default:
      image: dffw-controller
      flavor: m1.small
  ocp_master_params:
    type: json
    default:
      image: ipxe-boot-usb
      flavor: m1.xlarge
  compute_params:
    type: json
    default:
      image: CentOS-Stream-GenericCloud-9
      flavor: m1.large

resources:
  #
  # Networks
  #
  machine-net:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  machine-subnet:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: machine-net}
      ip_version: 4
      cidr: 192.168.32.0/24
      enable_dhcp: true
      dns_nameservers:
        - 192.168.32.254

  ctlplane-net:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  ctlplane-subnet:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: ctlplane-net}
      ip_version: 4
      cidr: 192.168.122.0/24
      enable_dhcp: false
      allocation_pools:
        - start: 192.168.122.100
          end: 192.168.122.150

  internal-api-net:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  internal-api-subnet:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: internal-api-net}
      ip_version: 4
      cidr: 172.17.0.0/24
      enable_dhcp: false
      allocation_pools:
        - start: 172.17.0.100
          end: 172.17.0.150

  storage-net:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  storage-subnet:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: storage-net}
      ip_version: 4
      cidr: 172.18.0.0/24
      enable_dhcp: false
      allocation_pools:
        - start: 172.18.0.100
          end: 172.18.0.150
  tenant-net:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  tenant-subnet:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: tenant-net}
      ip_version: 4
      cidr: 172.19.0.0/24
      enable_dhcp: false
      allocation_pools:
        - start: 172.19.0.100
          end: 172.19.0.150

  octavia-net:
    type: OS::Neutron::Net
    properties:
      port_security_enabled: false
  octavia-subnet:
    type: OS::Neutron::Subnet
    properties:
      network: {get_resource: octavia-net}
      ip_version: 4
      cidr: 172.23.0.0/24
      enable_dhcp: false
      allocation_pools:
        - start: 172.23.0.100
          end: 172.23.0.150

  #
  # Routers
  #
  router:
    type: OS::Neutron::Router
    properties:
      admin_state_up: true
      external_gateway_info:
        network: public
        enable_snat: true

  machine-net-router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: {get_resource: router} 
      subnet: {get_resource: machine-subnet}

  ctlplane-net-router-interface:
    type: OS::Neutron::RouterInterface
    properties:
      router: {get_resource: router} 
      subnet: {get_resource: ctlplane-subnet}

  #
  # Instances
  #
  users:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        users:
          - default
          - name: zuul
            geco: "Zuul user"
            sudo: ALL=(ALL) NOPASSWD:ALL
            ssh-authorized-keys: {get_param: ssh_pub_key}

  controller-write-files:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        write_files:
          - path: /etc/dnsmasq.conf
            content: |
              # dnsmasq service config
              # Include all files in /etc/dnsmasq.d except RPM backup files
              conf-dir=/etc/dnsmasq.d,.rpmnew,.rpmsave,.rpmorig
              no-resolv
            owner: root:dnsmasq
          - path: /etc/dnsmasq.d/forwarders.conf
            content: 
              str_replace:
                template: |
                  # DNS forwarders records
                  server=$dns1
                  server=$dns2
                params:
                  $dns1: {get_param: [dns_servers, 0]}
                  $dns2: {get_param: [dns_servers, 1]}
            owner: root:dnsmasq
          - path: /etc/dnsmasq.d/host_records.conf
            content: 
              str_replace:
                template: |
                  # Host records
                  host-record=controller-0.openstack.lab,$controller0
                  host-record=api.sno.openstack.lab,$master0
                  host-record=api-int.sno.openstack.lab,$master0
                  host-record=master-0.sno.openstack.lab,$master0
                params:
                  $controller0: {get_attr: [controller-machine-port, fixed_ips, 0, ip_address]}
                  $master0: {get_attr: [master0-machine-port, fixed_ips, 0, ip_address]}
            owner: root:dnsmasq
          - path: /etc/dnsmasq.d/wildcard_records.conf
            content: 
              str_replace:
                template: |
                  # Wildcard records
                  address=/apps.sno.openstack.lab/$addr
                params:
                  $addr: {get_attr: [master0-machine-port, fixed_ips, 0, ip_address]}
            owner: root:dnsmasq
          - path: /etc/resolv.conf
            content: |
              nameserver: 127.0.0.1
            owner: root:root
          - path: /etc/NetworkManager/conf.d/98-rc-manager.conf
            content: |
              [main]
              rc-manager=unmanaged
            owner: root:root

  controller-runcmd:
    type: OS::Heat::CloudConfig
    properties:
      cloud_config:
        runcmd:
          - ['systemctl', 'enable', 'dnsmasq.service']
          - ['systemctl', 'start', 'dnsmasq.service']
          - ['setenforce', 'permissive']
          - ['sed', '-i', 's/Listen 80/Listen 8081/g', '/etc/httpd/conf/httpd.conf']
          - ['systemctl', 'enable', 'httpd.service']
          - ['systemctl', 'start', 'httpd.service']

  controller-init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: {get_resource: users}
        - config: {get_resource: controller-write-files}
        - config: {get_resource: controller-runcmd}

  controller-machine-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: machine-net}
      fixed_ips:
        - ip_address: 192.168.32.254

  controller-floating-ip:
     depends_on: machine-net-router-interface
     type: OS::Neutron::FloatingIP
     properties:
       floating_network: public
       port_id: {get_resource: controller-machine-port}

  controller:
    type: OS::Nova::Server
    properties:
      key_name: {get_param: keypair}
      image: {get_param: [controller_params, image]}
      flavor: {get_param: [controller_params, flavor]}
      networks:
        - port: {get_resource: controller-machine-port}
      user_data_format: RAW
      user_data: {get_resource: controller-init}

  # OCP Masters
  
  # DHCP Opts value
  extra-dhcp-opts-value:
    type: OS::Heat::Value
    properties:
      type: json
      value:
        extra_dhcp_opts:
          - opt_name: "60"
            opt_value: "HTTPClient"
            ip_version: 4
          - opt_name: "67"
            opt_value: 
              str_replace:
                template: http://$server_address:8081/boot-artifacts/agent.x86_64.ipxe
                params:
                  $server_address: {get_attr: [controller-machine-port, fixed_ips, 0, ip_address]}


  master0-machine-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: machine-net}
      port_security_enabled: false
      fixed_ips:
        - ip_address: 192.168.32.10
      value_specs: {get_attr: [extra-dhcp-opts-value, value]}

  master0-ctlplane-trunk-parent-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: ctlplane-net}
      port_security_enabled: false
      fixed_ips:
        - ip_address: 192.168.122.10

  master0-internal-api-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: internal-api-net}
      port_security_enabled: false
      fixed_ips:
        - ip_address: 172.17.0.10

  master0-storage-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: storage-net}
      port_security_enabled: false
      fixed_ips:
        - ip_address: 172.18.0.10

  master0-tenant-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: tenant-net}
      port_security_enabled: false
      fixed_ips:
        - ip_address: 172.19.0.10

  master0-octavia-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: octavia-net}
      port_security_enabled: false
      fixed_ips:
        - ip_address: 172.23.0.10

  master0-trunk0:
    type: OS::Neutron::Trunk
    properties:
      port: {get_resource: master0-ctlplane-trunk-parent-port}
      sub_ports:
        - port: {get_resource: master0-internal-api-port}
          segmentation_id: 20
          segmentation_type: vlan
        - port: {get_resource: master0-storage-port}
          segmentation_id: 21
          segmentation_type: vlan
        - port: {get_resource: master0-tenant-port}
          segmentation_id: 22
          segmentation_type: vlan
        - port: {get_resource: master0-octavia-port}
          segmentation_id: 23
          segmentation_type: vlan

  master0:
    type: OS::Nova::Server
    properties:
      image: {get_param: [ocp_master_params, image]}
      flavor: {get_param: [ocp_master_params, flavor]}
      networks:
        - port: {get_resource: master0-machine-port}
        - port: {get_attr: [master0-trunk0, port_id]}

# Computes
  compute_init:
    type: OS::Heat::MultipartMime
    properties:
      parts:
        - config: {get_resource: users}

  compute0-ctlplane-trunk-parent-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: ctlplane-net}
      port_security_enabled: false
      fixed_ips:
        - ip_address: 192.168.122.100

  compute0-internal-api-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: internal-api-net}
      port_security_enabled: false
      fixed_ips:
        - ip_address: 172.17.0.100

  compute0-storage-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: storage-net}
      port_security_enabled: false
      fixed_ips:
        - ip_address: 172.18.0.100

  compute0-tenant-port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: tenant-net}
      port_security_enabled: false
      fixed_ips:
        - ip_address: 172.19.0.100

  compute0-trunk0:
    type: OS::Neutron::Trunk
    properties:
      port: {get_resource: compute0-ctlplane-trunk-parent-port}
      sub_ports:
        - port: {get_resource: compute0-internal-api-port}
          segmentation_id: 20
          segmentation_type: vlan
        - port: {get_resource: compute0-storage-port}
          segmentation_id: 21
          segmentation_type: vlan
        - port: {get_resource: compute0-tenant-port}
          segmentation_id: 22
          segmentation_type: vlan

  compute0:
    type: OS::Nova::Server
    properties:
      key_name: {get_param: keypair}
      image: {get_param: [compute_params, image]}
      flavor: {get_param: [compute_params, flavor]}
      networks:
        - port: {get_attr: [compute0-trunk0, port_id]}
      user_data_format: RAW
      user_data: {get_resource: compute_init}
      config_drive: true

outputs:
  controller_floating_ip:
    description: Controller Floating IP
    value: {get_attr: [controller-floating-ip, floating_ip_address]}

  sushy_emulator_uuids:
    description: UUIDs of instances to manage with sushy-tools - RedFish virtual BMC
    value:
      compute0: {get_resource: compute-0}

  ocp_install_config:
    description: OCP install-config.yaml
    value:
      apiVersion: v1
      baseDomain: openstack.lab
      controlPlane:
        architecture: amd64
        hyperthreading: Disabled
        name: master
        replicas: 1
      compute:
        - architecture: amd64
          hyperthreading: Disabled
          name: worker
          replicas: 0
      metadata:
        name: sno
      networking:
        clusterNetwork:
          - cidr: 10.128.0.0/16
            hostPrefix: 23
        machineNetwork:
          - cidr: {get_attr: [machine-subnet, cidr]}
        serviceNetwork:
          - 172.30.0.0/16
        networkType: OVNKubernetes
      platform:
        none: {}
      pullSecret: _replaced_
      sshKey: {get_param: ssh_pub_key}

  ocp_agent_config:
    description: OCP agent-config.yaml
    value:
      apiVersion: v1beta1
      kind: AgentConfig
      metadata:
        name: sno
      rendezvousIP: {get_attr: [master0-machine-port, fixed_ips, 0, ip_address]}
      additionalNTPSources: {get_param: ntp_servers}
      bootArtifactsBaseURL: 
        str_replace:
          template: http://$server_address:8081/boot-artifacts
          params:
            $server_address: {get_attr: [controller-machine-port, fixed_ips, 0, ip_address]}
      hosts:
        - hostname: master-0
          role: master
          interfaces:
            - name: ens3
              macAddress: {get_attr: [master0-machine-port, mac_address]}
          networkConfig:
            interfaces:
              - name: ens3
                type: ethernet
                state: up
                mac-address: {get_attr: [master0-machine-port, mac_address]}
                ipv4:
                  enabled: true
                  dhcp: true
                ipv6:
                  enabled: false

  controller_ansible_host:
    description: >
      Controller ansible host, this struct can be passed to the ansible.builtin.add_host module
    value:
      name: controller-0
      ansible_ssh_user: zuul
      ansible_host: {get_attr: [controller-floating-ip, floating_ip_address]}
      ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
      groups: controllers

  ansible_inventory:
    description: Ansible inventory
    value:
      all:
        children:
          controllers:
            vars:
          ocps:
            vars:
          computes:
            vars:
      localhosts:
        hosts:
          localhost:
            ansible_connection: local
      controllers:
        hosts:
          controller0:
            ansible_host: {get_attr: [controller-machine-port, fixed_ips, 0, ip_address]}
            ansible_user: zuul
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
            ansible_ssh_private_key_file: '~/.ssh/id_rsa'
      ocps:
        hosts:
          master0:
            ansible_host: {get_attr: [master0-machine-port, fixed_ips, 0, ip_address]}
            ansible_user: core
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
            ansible_ssh_private_key_file: '~/.ssh/id_rsa'
      computes:
        hosts:
          compute0:
            ansible_host: {get_attr: [compute0-ctlplane-trunk-parent-port, fixed_ips, 0, ip_address]}
            ansible_user: zuul
            ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
            ansible_ssh_private_key_file: '~/.ssh/id_rsa'
