- name: Controller
  count: 1
  hostname_format: controller-%index%
  defaults:
    networks:
      - network: external
      - network: internalapi
      - network: storage
      - network: storagemgmt
      - network: tenant

- name: Compute
  count: 1
  hostname_format: compute-%index%
  defaults:
    networks:
      - network: internalapi
      - network: tenant
      - network: storage

