- name: Controller
  count: 1
  hostname_format: controller-%index%
  defaults:
    networks:
      - network: external
      - network: internalapi
      - network: storage
      - network: storagemgmt
      - network: tenant
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
      default_route_network:
        - external
- name: Compute
  count: 1
  hostname_format: compute-%index%
  defaults:
    networks:
      - network: internalapi
      - network: tenant
      - network: storage
    network_config:
      template: templates/multiple_nics/multiple_nics_dvr.j2
