- hosts: undercloud
  vars_prompt:
  - name: rhn_username
    prompt: "RHN Username?"
    private: no
  - name: rhn_password
    prompt: "RHN password?"
  tasks:
  - name: Set up some swap space
    become: yes
    shell: |
      dd if=/dev/zero of=/opt/8GB.swap bs=8192 count=1048576
      mkswap /opt/8GB.swap
      swapon /opt/8GB.swap
      echo "/opt/8GB.swap swap                                    swap    defaults 0 0" >> /etc/fstab
  - name: Set up public interface
    become: yes
    copy:
      content: | 
        NAME=eth2
        DEVICE=eth2
        BOOTPROTO=static
        IPADDR={{ undercloud_public_ip }}
        PREFIX=24
        MTU=1442
      dest: /etc/sysconfig/network-scripts/ifcfg-eth2
  - name: Bring up public interface
    become: yes
    command: ifup eth2
  - name: Register node
    become: yes
    shell: |
      subscription-manager register --username {{ rhn_username }} --password {{ rhn_password }}
      subscription-manager role --set="Red Hat Enterprise Linux Server"
      subscription-manager service-level --set="Self-Support"
      subscription-manager usage --set="Development/Test"
      subscription-manager attach --pool=8a85f98c60c2c2b40160c324e5d21d70
  - name: Set up repos
    become: yes
    shell: |
      subscription-manager repos --disable=*
      sudo subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms --enable=rhel-ha-for-rhel-7-server-rpms --enable=rhel-7-server-openstack-13-rpms --enable=rhel-7-server-rhceph-3-tools-rpms
  - name: Install packages
    become: yes
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - git
        - tmux
        - vim-enhanced
  - name: upgrade all packages
    become: yes
    yum:
      name: '*'
      state: latest
  - name: Unconditionally reboot the machine with all defaults
    become: yes
    reboot:
  - name: Install tripleo client
    become: yes
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - python-tripleoclient
        - python-novajoin
  - name: Git checkout labs
    git:
      repo: https://github.com/hjensas/homelab.git
      dest: "{{ ansible_env.HOME }}/homelab"
  - name: Git checkout tripleo-heat-templates
    git:
      repo: https://opendev.org/openstack/tripleo-heat-templates.git
      dest: "{{ ansible_env.HOME }}/tripleo-heat-templates"
      # refspec: refs/changes/49/619649/10
      # version: FETCH_HEAD
  - name: Create symlinks
    file:
      src: "{{ ansible_env.HOME }}/homelab/labs/ovb-ipv4-tls-e-routed/{{ item }}"
      dest: "{{ ansible_env.HOME }}/{{ item }}"
      state: link
    with_items:
      - overcloud
  - name: Create symlinks undercloud
    file:
      src: "{{ ansible_env.HOME }}/homelab/labs/ovb-ipv4-tls-e-routed/undercloud/{{ item }}"
      dest: "{{ ansible_env.HOME }}/{{ item }}"
      state: link
    with_items:
      - undercloud.conf
  - name: Use FreeIPA for nameservices
    become: yes
    copy:
      dest: /etc/resolv.conf
      contenet: |
        search tls.example.com
        nameserver {{ freeipa_ip }}
  - name: IPA Join
    become: yes
    shell: |
      /usr/libexec/novajoin-ipa-setup \
        --principal admin \
        --password {{ ipa_password }} \
        --server freeipa.tls.example.com \
        --realm TLS.EXAMPLE.COM \
        --domain tls.example.com \
        --hostname undercloud.tls.example.com \
        --precreate
    register:
      ipa_otp
  - name: Set undercloud.conf otp
    replace:
      path: "{{ ansible_env.HOME }}/undercloud.conf"
      regexp: <otp>
      replace: "{{ ipa_otp.stdout }}"
  - name: set undercloud.conf nameservers
    replace:
      path: "{{ ansible_env.HOME }}/undercloud.conf"
      regexp: <freeipa_ip>
      replace "{{ freeipa_ip }}"
  - name: Create images directory
    file:
      dest: "{{ ansible_env.HOME }}/images"
      state: directory
  - name: Install Undercloud
    shell:
      openstack undercloud install
#  - name: Upload overcloud images
#    shell: |
#      source {{ ansible_env.HOME }}/stackrc
#      cd {{ ansible_env.HOME }}/images
#      openstack overcloud image upload
#  - name: Import nodes
#    shell: |
#      source {{ ansible_env.HOME }}/stackrc
#      openstack overcloud node import instackenv.json
#  - pause:
#      minutes: 1
#  - name: Introspect and provide nodes
#    shell: |
#      source {{ ansible_env.HOME }}/stackrc
#      openstack overcloud node introspect --all-manageable --provide
#  - name: Set node capabilities
#    shell: |
#      source ~/stackrc
#      openstack baremetal node set --property capabilities='profile:control,boot_option:local' baremetal-{{ idnum }}-leaf1-0
#      openstack baremetal node set --property capabilities='profile:control,boot_option:local' baremetal-{{ idnum }}-leaf1-1
#      openstack baremetal node set --property capabilities='profile:control,boot_option:local' baremetal-{{ idnum }}-leaf1-2
#      openstack baremetal node set --property capabilities='profile:compute-leaf2,boot_option:local' baremetal-{{ idnum }}-leaf2-0
#      openstack baremetal node set --property capabilities='profile:compute-leaf2,boot_option:local' baremetal-{{ idnum }}-leaf2-1
#
