- hosts: undercloud
  tasks:
  - name: Set up some swap space
    become: yes
    shell: |
      dd if=/dev/zero of=/opt/8GB.swap bs=8192 count=1048576
      mkswap /opt/8GB.swap
      swapon /opt/8GB.swap
      echo "/opt/8GB.swap swap                                    swap    defaults 0 0" >> /etc/fstab
  - name: Set up public interface
    become: yes
    copy:
      content: | 
        NAME=eth2
        DEVICE=eth2
        BOOTPROTO=static
        IPADDR={{ undercloud_public_ip }}
        PREFIX=24
        MTU=1442
      dest: /etc/sysconfig/network-scripts/ifcfg-eth2
  - name: Install packages
    become: yes
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - git
        - tmux
        - vim-enhanced
  - name: Install tripleo repos rpm
    become: yes
    shell: |
      dnf install -y https://trunk.rdoproject.org/centos9/component/tripleo/current/python3-tripleo-repos-0.1.1-0.20220125231326.c5df4a6.el9.noarch.rpm
  - name: Set up tripleo repos
    become: yes
    shell:
      tripleo-repos current-tripleo ceph
  - name: upgrade all packages
    become: yes
    yum:
      name: '*'
      state: latest
  - name: Unconditionally reboot the machine with all defaults
    become: yes
    reboot:
  - name: Install tripleo client
    become: yes
    yum:
      name: "{{ packages }}"
    vars:
      packages:
        - python3-tripleoclient
  - name: Git checkout labs
    git:
      repo: https://github.com/hjensas/homelab.git
      dest: "{{ ansible_env.HOME }}/homelab"
  - name: Git checkout tripleo-heat-templates
    git:
      repo: https://opendev.org/openstack/tripleo-heat-templates.git
      dest: "{{ ansible_env.HOME }}/tripleo-heat-templates"
      # refspec: refs/changes/49/619649/10
      # version: FETCH_HEAD
  - name: Create symlinks
    file:
      src: "{{ ansible_env.HOME }}/homelab/labs/ovb-ipv4-cs9/{{ item }}"
      dest: "{{ ansible_env.HOME }}/{{ item }}"
      state: link
    with_items:
      - overcloud
  - name: Create symlinks undercloud
    file:
      src: "{{ ansible_env.HOME }}/homelab/labs/ovb-ipv4-cs9/undercloud/{{ item }}"
      dest: "{{ ansible_env.HOME }}/{{ item }}"
      state: link
    with_items:
      - undercloud.conf
  - name: Create images directory
    file:
      dest: "{{ ansible_env.HOME }}/images"
      state: directory
  - name: Downlaod images
    shell: |
      cd {{ ansible_env.HOME }}/images
      curl -O https://images.rdoproject.org/centos9/master/rdo_trunk/current-tripleo/ironic-python-agent.tar
      curl -O https://images.rdoproject.org/centos9/master/rdo_trunk/current-tripleo/overcloud-hardened-uefi-full.qcow2
      tar xvf ironic-python-agent.tar
  - name: Install Undercloud
    shell:
      openstack undercloud install
  - name: Upload overcloud images
    shell: |
      source {{ ansible_env.HOME }}/stackrc
      cd {{ ansible_env.HOME }}/images
      openstack overcloud image upload
  - name: Import nodes
    shell: |
      source {{ ansible_env.HOME }}/stackrc
      openstack overcloud node import instackenv.json
  - pause:
      minutes: 1
  - name: Introspect and provide nodes
    shell: |
      source {{ ansible_env.HOME }}/stackrc
      openstack overcloud node introspect --all-manageable --provide
#   - name: Set node capabilities
#     shell: |
#       source ~/stackrc
#       openstack baremetal node set --property capabilities='profile:control,boot_option:local' baremetal-{{ idnum }}-leaf1-0
#       #openstack baremetal node set --property capabilities='profile:control,boot_option:local' baremetal-{{ idnum }}-leaf1-1
#       #openstack baremetal node set --property capabilities='profile:control,boot_option:local' baremetal-{{ idnum }}-leaf1-2
#       openstack baremetal node set --property capabilities='profile:compute-leaf2,boot_option:local' baremetal-{{ idnum }}-leaf2-0
#       #openstack baremetal node set --property capabilities='profile:compute-leaf2,boot_option:local' baremetal-{{ idnum }}-leaf2-1
# 
