- name: Overcloud Node Pre Network Tasks
  hosts: allovercloud
  any_errors_fatal: true
  gather_facts: false
  tasks:
  - name: Install packages
    become: true
    dnf:
      name:
      - openvswitch
      - os-net-config
      state: present
