
heat_template_version: rocky
description: >
  Software Config to drive os-net-config to configure multiple interfaces for the CephStorage role.
parameters:
  ControlPlaneIp:
    default: ''
    description: IP address/subnet on the ctlplane network
    type: string
  ControlPlaneSubnetCidr:
    default: ''
    description: >
      The subnet CIDR of the control plane network. (The parameter is
      automatically resolved from the ctlplane subnet's cidr attribute.)
    type: string
  ControlPlaneDefaultRoute:
    default: ''
    description: The default route of the control plane network. (The parameter
      is automatically resolved from the ctlplane subnet's gateway_ip attribute.)
    type: string
  ControlPlaneStaticRoutes:
    default: []
    description: >
      Routes for the ctlplane network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  ControlPlaneMtu:
    default: 1500
    description: The maximum transmission unit (MTU) size(in bytes) that is
      guaranteed to pass through the data path of the segments in the network.
      (The parameter is automatically resolved from the ctlplane network's mtu attribute.)
    type: number

  Storage2IpSubnet:
    default: ''
    description: IP address/subnet on the storage2 network
    type: string
  Storage2NetworkVlanID:
    default: 21
    description: Vlan ID for the storage2 network traffic.
    type: number
  Storage2Mtu:
    default: 1450
    description: The maximum transmission unit (MTU) size(in bytes) that is
      guaranteed to pass through the data path of the segments in the
      Storage2 network.
    type: number
  Storage2InterfaceRoutes:
    default: []
    description: >
      Routes for the storage2 network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json
  StorageMgmt2IpSubnet:
    default: ''
    description: IP address/subnet on the storage_mgmt2 network
    type: string
  StorageMgmt2NetworkVlanID:
    default: 31
    description: Vlan ID for the storage_mgmt2 network traffic.
    type: number
  StorageMgmt2Mtu:
    default: 1450
    description: The maximum transmission unit (MTU) size(in bytes) that is
      guaranteed to pass through the data path of the segments in the
      StorageMgmt2 network.
    type: number
  StorageMgmt2InterfaceRoutes:
    default: []
    description: >
      Routes for the storage_mgmt2 network traffic.
      JSON route e.g. [{'destination':'10.0.0.0/16', 'nexthop':'10.0.0.1'}]
      Unless the default is changed, the parameter is automatically resolved
      from the subnet host_routes attribute.
    type: json

  DnsServers: # Override this via parameter_defaults
    default: []
    description: >
      DNS servers to use for the Overcloud (2 max for some implementations).
      If not set the nameservers configured in the ctlplane subnet's
      dns_nameservers attribute will be used.
    type: comma_delimited_list
  DnsSearchDomains: # Override this via parameter_defaults
    default: []
    description: A list of DNS search domains to be added (in order) to resolv.conf.
    type: comma_delimited_list
resources:
  OsNetConfigImpl:
    type: OS::Heat::SoftwareConfig
    properties:
      group: script
      config:
        str_replace:
          template:
            get_file: /home/centos/tripleo-heat-templates/network/scripts/run-os-net-config.sh
          params:
            $network_config:
              network_config:
              - type: interface
                name: nic1
                mtu:
                  get_param: ControlPlaneMtu
                use_dhcp: false
                dns_servers:
                  get_param: DnsServers
                domain:
                  get_param: DnsSearchDomains
                addresses:
                - ip_netmask:
                    list_join:
                    - /
                    - - get_param: ControlPlaneIp
                      - get_param: ControlPlaneSubnetCidr
                routes:
                  list_concat_unique:
                    - get_param: ControlPlaneStaticRoutes
                    - - default: true
                        next_hop:
                          get_param: ControlPlaneDefaultRoute
              - type: interface
                name: nic4
                mtu:
                  get_param: Storage2Mtu
                use_dhcp: false
                addresses:
                - ip_netmask:
                    get_param: Storage2IpSubnet
                routes:
                  list_concat_unique:
                    - get_param: Storage2InterfaceRoutes
              - type: interface
                name: nic5
                mtu:
                  get_param: StorageMgmt2Mtu
                use_dhcp: false
                addresses:
                - ip_netmask:
                    get_param: StorageMgmt2IpSubnet
                routes:
                  list_concat_unique:
                    - get_param: StorageMgmt2InterfaceRoutes
outputs:
  OS::stack_id:
    description: The OsNetConfigImpl resource.
    value:
      get_resource: OsNetConfigImpl
