parameter_defaults:
    # -------------------------------------------------------------------------
    # Control Plane subnet is used to get the VIPs,
    #    VIPs need to be on same network as controllers.
    # -------------------------------------------------------------------------
    NeutronBridgeMappings: datacentre:br-ex,tenant:br-isolated,baremetal:br-baremetal
    NeutronFlatNetworks: datacentre,baremetal
    NeutronExternalNetworkBridge: ''
    NeutronNetworkType: geneve
    NeutronNetworkVLANRanges: tenant:1000:2000
    NeutronTunnelTypes: geneve

    NetworkDeploymentActions: ['CREATE','UPDATE']


    ServiceNetMap:
      IronicApiNetwork: oc_provisioning
      IronicNetwork: oc_provisioning
